### ISSUE TITLE
.env file does not seem to 'take' for port change

### ISSUE THREAD

**Issue by adamtyoung** [harvard-edtech/caccl-api#18]
Hello,
  I am trying to change the default port from 443 to 8443, but it doesn't seem to read the .env file that I have placed in the root dir. The file just contains ```PORT=8443```.

**Comment by gabeabrams** [comment]
Unfortunately, creating a `.env` is not the same thing as setting environment variables. I'm assuming you're trying to use this library:
https://www.npmjs.com/package/dotenv

In which case, you'll need to read their docs.
